### ISSUE TITLE
FaceFX doesn't compile under nonunity/IWYU

### ISSUE THREAD

**Issue by dwrpayne** [FaceFX/FaceFX-UE4#109]
We have a non-unity build to verify our IWYU setup, and it breaks on FaceFX.

https://docs.unrealengine.com/latest/INT/Programming/UnrealBuildSystem/IWYUReferenceGuide/

I have a change that fixes all the cpp files to correctly include just the files they use. Would you take a pull request on this?

**Comment by jcredmond** [comment]
Sure, we take pull requests as long as your changes are MIT licensed. We need to make sure the code continues to compile normally and in the “rocket” build (building for the Epic installer pre-compiled version of the engine). A few engine versions ago there were some PCH handling differences between GitHub source compiles and rocket builds.

**Comment by dwrpayne** [comment]
Thank for the quick response! I'll get you something this week.

I'm not familiar with rocket builds as I build the engine from source. Do
you have Travis set up or is there an easy way I can test rocket builds
locally?

On Nov 30, 2017 12:01 PM, "Jamie Redmond" <notifications@github.com> wrote:

Sure, we take pull requests as long as your changes are MIT licensed. We
need to make sure the code continues to compile normally and in the
“rocket” build (building for the Epic installer pre-compiled version of the
engine). A few engine versions ago there were some PCH handling differences
between GitHub source compiles and rocket builds.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FaceFX/FaceFX-UE4/issues/109#issuecomment-348303745>,
or mute the thread

**Comment by jcredmond** [comment]
No, we don't have Travis set up. The rocket build requires the Epic installer version of the engine to be installed and that is actually what builds the plugin.

I'll test the rocket build when you submit the PR and if there are any problems I'll point you in the right direction.

Make sure you are on the latest UE4 (4.18), and please make sure your changes compile on Windows and on Mac.
