### ISSUE TITLE
Incompatible animation error dragging Sequencer event over current time

### ISSUE THREAD

**Issue by dpakatheman** [FaceFX/FaceFX-UE4#129]
This is a tricky bug to reproduce, but I have reproduced it semi-consistently on PC, OSX, and with several different levels/characters.

The bug occurs when you drag a FaceFX sequencer event over the current time selector (by default this is at time=0).  You can drag the whole event, or you can drag only the start time, either will trigger it.  If you have the Output log window open when the bug occurs, as you are dragging around the sequencer event in negative time, you will see something like the following getting spammed to the log:

```
LogFaceFX: Warning: UFaceFXCharacter::Play. Animation is not compatible with FaceFX actor handle. Actor: SladeFaceFX. Animation: SladeFaceFX_Default_welcome
LogFaceFX: Error: UFaceFXCharacter::JumpTo. Current animation is invalid. Asset: SladeFaceFX
LogFaceFX: Warning: UFaceFXCharacter::Play. Animation is not compatible with FaceFX actor handle. Actor: SladeFaceFX. Animation: SladeFaceFX_Default_welcome
LogFaceFX: Warning: UFaceFXCharacter::Play. Animation is not compatible with FaceFX actor handle. Actor: SladeFaceFX. Animation: SladeFaceFX_Default_welcome
LogFaceFX: Warning: UFaceFXCharacter::Play. Animation is not compatible with FaceFX actor handle. Actor: SladeFaceFX. Animation: SladeFaceFX_Default_welcome
```
When you move the sequencer event back into positive time and away from the current time selector, you can drag it around without getting any warnings or errors. 

To reproduce, I load up a level with a level sequence playing a FaceFX animation that starts at time greater than 0, and open sequencer and the Output log. Before I move the sequencer event into negative time however, I  have to perform some other steps.  At minimum, I've performed a Launch operation and waited for the launch to play before trying to trigger the rest of the bug. I do not know if performing the Launch operation is required to trigger the bug, (perhaps it is a garbage collection issue and Launch is simply triggering some sort of memory cleanup that could happen in other scenarios).

At this point, I'm fairly confident that I will not be able to find a 100% reproducible test case, and I believe some sort of memory issue is to blame for the randomness.  I am also confident that if we fix the bug, I will be able to confirm that the bug is fixed because I can reproduce the bug sufficiently frequently that the absence of the bug after a day or two of testing will indicate it is fixed.

**Comment by dpakatheman** [comment]
I have edited the bug to reflect that having a start time < 0 does not cause the bug.  The "current time" is by default=0, so dragging into negative time was forcing a preview update because the sequencer event impacted the current time.  Evaluating the FaceFX animations caused the error, not that the animations had start times < 0.

**Comment by dpakatheman** [comment]
related bug #131 was filed.  Although I have not been able to reproduce this #129 for the past 2 days, I have been reproducing #131 and the similarities make me confident that my initial assertion that sequencer event start times < 0 were at fault was incorrect.  Dragging the event over time=0 was simply causing an update to the character because the current time marker was at 0.

**Comment by dpakatheman** [comment]
Reproduced in 4.19 ( Build: ++UE4+Release-4.19-CL-4033788 )
Confirmed that dragging the event over the current time marker triggers it, not having start time < 0.

**Comment by jcredmond** [comment]
See #133.
