### ISSUE TITLE
Is there a way to move the plugin settings from FaceFX.ini file into the Plugins section of the Project Settings in UnrealEd?

### ISSUE THREAD

**Issue by jcredmond** [FaceFX/FaceFX-UE4#134]
Currently there is a FaceFX.ini file that controls some plugin settings. It would be nice if we could replace that file with an interface in the Plugins section of the Project Settings in UnrealEd.

![pluginsettings](https://user-images.githubusercontent.com/4458771/44199242-d5ffec00-a143-11e8-9a0f-cc7dfd8aaa65.png)

Is there a way to add to that section from a plugin without modifying the core engine?

**Comment by jcredmond** [comment]
Fixed in 1a085051.

**Comment by dpakatheman** [comment]
I'm reopening this because we need to update the Documentation.  We still reference the FaceFX.ini file here: 

https://github.com/FaceFX/FaceFX-UE4/blob/master/Documentation/Configuration.md
