### ISSUE TITLE
Add support for animating morph targets

### ISSUE THREAD

**Issue by jcredmond** [FaceFX/FaceFX-UE4#14]
The user should be able to wire FaceFX animation data up to morph targets in UE4.

**Comment by nate1380** [comment]
Is there an eta on this feature?

**Comment by jcredmond** [comment]
Not currently, sorry. We're working on matinee support at the moment. Pull requests or other contributions are always welcome.

**Comment by nate1380** [comment]
That's a bummer, we just purchased FaceFX studio to do exactly this.  Is there a workaround to at least export baked animations from FaceFX and import them as animations in UE4 to our existing skeletons?

**Comment by jcredmond** [comment]
Morph support is coming, I just can't give you an exact date. The FaceFX Runtime supports everything, it's just the UE4 glue that needs the support -- the UE4 integration docs mention that the UE4 integration currently requires a bones-based character to work. You can always export an FBX file from FaceFX Studio and import it into UE4 in the interim.

**Comment by jcredmond** [comment]
I think we'll have this in this week or next week, fyi.

**Comment by nate1380** [comment]
Oh awesome, great news!
