### ISSUE TITLE
Negative-time keys cause end of audio to be clipped in Sequencer

### ISSUE THREAD

**Issue by dpakatheman** [FaceFX/FaceFX-UE4#142]
When a FaceFX animation starts in negative time, the amount of negative time is truncated from the audio when the animation plays from sequencer (or matinee).   So the result is that the audio is slightly clipped at the end during playback. 

Normally the amount of negative time in an animation is small, so this can be difficult to detect, but in the attached file, Slade's welcome animation has been modified so that his head starts moving at around -3.0 seconds.  Audio starts at time 0 (as always), so there is 3 seconds of head movement prior to the moving of the lips or playing audio.   Because of the negative time, if you play this animation from sequencer, the audio chops off the last 3 seconds.

For the FBX and texture files see [here](https://unreal.facefx.com/FaceFX-UE4-Sample-Content.zip), but be sure to use the .facefx and SladeFaceFX.ffxc folder from the attached:

[SladeNegativeTimeKeys.zip](https://github.com/FaceFX/FaceFX-UE4/files/2329933/SladeNegativeTimeKeys.zip)

Happens when the animation is triggered from Sequencer & Matinee, but not Blueprint.

Happens in 4.19 & latest.

**Comment by jcredmond** [comment]
@dpakatheman close this out when you verify.

**Comment by dpakatheman** [comment]
I'm still getting the audio (and animation) clipped in my test case.

**Comment by jcredmond** [comment]
Confirmed fixed.

**Comment by dpakatheman** [comment]
New sequencer events are now created correctly, but due to #148 the old events will remain incorrect.
