### ISSUE TITLE
Failing to install latest compiler with UE4.21 needs custom warning

### ISSUE THREAD

**Issue by dpakatheman** [FaceFX/FaceFX-UE4#153]
Starting with UE4.21, the FaceFX Runtime version 1.5 is required.  The 1.5 ffxc compiler and FaceFX Studio plugin must be used to generate animation data that is imported into UE4.21. The old compiler stored animation data in separate folders for each platform (x86, ps4, etc), but the new compiler outputs only a single copy of each animation with no subfolders.  The binary file format did not change, but the folder structure in the .ffxc folder did.

Failure to install the updated FaceFX compiler as a FaceFX Studio plugin will result in an error upon importing a .facefx file into UE4 like:

`Loading compiled data failed.  File doesn't exist: __path_to__file__`

This behavior is correct, but we should be more specific and detect the old folder structure and provide a specific warning.  The absence of a .ffxactor file combined with the presence of an x86 folder in the .ffxc folder is a clear sign that the old compiler was used.  This could result in a message like:

Legacy compiler output detected.  Please upgrade your FaceFX Studio Runtime compiler to the latest version.

**Comment by jcredmond** [comment]
@dpakatheman do think we can just close this? I don't see the purpose in fixing this since it shouldn't be a problem now as everyone is likely on a newer version anyway.
