### ISSUE TITLE
Pasting a FaceFX Animation key in sequencer crashes UnrealEd

### ISSUE THREAD

**Issue by dpakatheman** [FaceFX/FaceFX-UE4#181]
Open sequencer, and add a FaceFX animation key if needed.  Cut or Copy the key.  Make sure the FaceFX Track is selected, then Ctrl + V or right-click to paste.  UnrealEd crashes.

**Comment by jcredmond** [comment]
Fixed in https://github.com/jcredmond/FaceFX-UE4/commit/a75bbccdfc7d2692d0a8bc50a36bc17851450d16

**Comment by jcredmond** [comment]
Fixed in 4.26 plugin.
