### ISSUE TITLE
Packaging Failure

### ISSUE THREAD

**Issue by nate1380** [FaceFX/FaceFX-UE4#19]
Currently get build failures when trying to package a project with FaceFX enabled:

"MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: Couldn't find module rules file for module 'FaceFX'."

Output log:

MainFrameActions: Packaging (Windows (64-bit)): Project.Build: ********** BUILD COMMAND STARTED **********
MainFrameActions: Packaging (Windows (64-bit)): InternalUtils.SafeFileExists: SafeFileExists C:\Program Files (x86)\Xoreax\IncrediBuild\xgConsole.exe=False
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: XGE was requested, but is unavailable, so we won't use it.
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* UE4Build:
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* ForceMonolithic: False
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* ForceNonUnity:False 
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* ForceDebugInfo: False
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* UseXGE: False
MainFrameActions: Packaging (Windows (64-bit)): InternalUtils.SafeFileExists: SafeFileExists D:\Program Files\Epic Games\4.8\Engine\Binaries\DotNET\UnrealBuildTool.exe=True
MainFrameActions: Packaging (Windows (64-bit)): InternalUtils.SafeFileExists: SafeFileExists D:\Program Files\Epic Games\4.8\Engine\Binaries\DotNET\UnrealBuildTool.exe=True
MainFrameActions: Packaging (Windows (64-bit)): InternalUtils.SafeFileExists: SafeFileExists D:\Program Files\Epic Games\4.8\Engine\Binaries\DotNET\UnrealBuildTool.exe=True
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.Run: Run: D:\Program Files\Epic Games\4.8\Engine\Binaries\DotNET\UnrealBuildTool.exe Klepto Win64 Development -clean "D:\Unreal Projects\Klepto\Klepto.uproject"  -nobuilduht -rocket -NoHotReloadFromIDE
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: Couldn't find module rules file for module 'FaceFX'.
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 3.2881881s to run UnrealBuildTool.exe, ExitCode=5
MainFrameActions: Packaging (Windows (64-bit)): ErrorReporter.Error: ERROR: AutomationTool error: Command failed (Result:5): D:\Program Files\Epic Games\4.8\Engine\Binaries\DotNET\UnrealBuildTool.exe Klepto Win64 Development -clean "D:\Unreal Projects\Klepto\Klepto.uproject"  -nobuilduht -rocket -NoHotReloadFromIDE. See logfile for details: 'UnrealBuildTool.txt' 
MainFrameActions: Packaging (Windows (64-bit)): BuildCommand.Execute: ERROR: BUILD FAILED
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: ERROR: AutomationTool terminated with exception:
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: ERROR: Exception in AutomationTool: Command failed (Result:5): D:\Program Files\Epic Games\4.8\Engine\Binaries\DotNET\UnrealBuildTool.exe Klepto Win64 Development -clean "D:\Unreal Projects\Klepto\Klepto.uproject"  -nobuilduht -rocket -NoHotR
MainFrameActions: Packaging (Windows (64-bit)): eloadFromIDE. See logfile for details: 'UnrealBuildTool.txt' 
MainFrameActions: Packaging (Windows (64-bit)): Stacktrace:    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.CleanWithUBT(String ProjectName, String TargetName, UnrealTargetPlatform Platform, String Config, String UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InForceNonUnity, Boolean InForceUnity, Dictionary`2 PlatformEnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL)
MainFrameActions: Packaging (Windows (64-bit)):    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
MainFrameActions: Packaging (Windows (64-bit)):    at BuildCommand.Execute()
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Process(String[] CommandLine)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Program.MainProc(Object Param)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.InternalUtils.RunSingleInstance(MainProc Main, Object Param)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Program.Main()
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: ERROR: Command failed (Result:5): D:\Program Files\Epic Games\4.8\Engine\Binaries\DotNET\UnrealBuildTool.exe Klepto Win64 Development -clean "D:\Unreal Projects\Klepto\Klepto.uproject"  -nobuilduht -rocket -NoHotReloadFromIDE. See logfile for details: 'UnrealBuildTool.txt' 
MainFrameActions: Packaging (Windows (64-bit)): ProcessManager.KillAll: Trying to kill 0 spawned processes.
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: AutomationTool exiting with ExitCode=5
MainFrameActions: Packaging (Windows (64-bit)): Domain_ProcessExit
MainFrameActions: Packaging (Windows (64-bit)): ProcessManager.KillAll: Trying to kill 0 spawned processes.
MainFrameActions: Packaging (Windows (64-bit)): copying UAT log files...
MainFrameActions: Packaging (Windows (64-bit)): RunUAT.bat ERROR: AutomationTool was unable to run successfully.
MainFrameActions: Packaging (Windows (64-bit)): BUILD FAILED

**Comment by jcredmond** [comment]
Are you using the pre-built FaceFX plugin binaries, or did you build from source yourself?

**Comment by nate1380** [comment]
All pre-built, UE 4.8.3 binary as well.

**Comment by jcredmond** [comment]
It looks like packaging is actually doing a compile, so you need the source code present (which the pre-built binaries don't have). Even after putting the source there, I get some other UBT error that seems to not having anything to do with FaceFX. We'll investigate.

**Comment by nate1380** [comment]
I gave that a try and see the same thing.  UBT also seemed to be looking for a missing folder in the source:

MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: FaceFX: Cannot find FaceFX Folder 'D:\Program Files\Epic Games\4.8\Engine\Plugins\Runtime\FaceFX\Source\FaceFXLib\facefx-runtime-1.0.0/facefx'

**Comment by jcredmond** [comment]
You need to download the runtime and put it in that folder separately. See README.md, in the section titled Source (under Installation).

**Comment by jcredmond** [comment]
Try using the latest Build.cs files (make sure you have installed the runtime libs like the README mentions).

**Comment by oliverzx** [comment]
Packaging for Windows x64 works for me using the plugin source and runtime lib files delivered by OC3.

**Comment by jcredmond** [comment]
Oliver, the issue is with the Epic Launcher installed version of the engine. TargetPlatform and DesktopPlatform are not allowed to be linked there -- and there is a bug in UE4, just verified by Epic, where the Build.cs files for plugins are required during packaging (thus requiring source to be present, even for pre-built binary plugins). It's not an issue if you build from source yourself from GitHub.

**Comment by nate1380** [comment]
That did the trick, successful build.  Thanks so much!
