### ISSUE TITLE
Unreal Engine 4.9 build fails

### ISSUE THREAD

**Issue by nate1380** [FaceFX/FaceFX-UE4#33]
Assuming this is a quick fix.  Getting this error when trying to rebuild plugin for 4.9.

Error	1	error : Module rules for 'FaceFXEditor' should not be dependent on modules which are also dynamically loaded: AssetTools	D:\UE4 Source\UnrealEngine-release\Engine\Intermediate\ProjectFiles\EXEC	UE4

**Comment by jcredmond** [comment]
Unfortunately, it's not a quick fix. That is just the first error in a spew of errors that building with 4.9 generates. We're looking into it.

**Comment by nate1380** [comment]
Ah ok...wishful thinking I guess.  Thanks!
