### ISSUE TITLE
Win32 Development linker error

### ISSUE THREAD

**Issue by eirland** [FaceFX/FaceFX-UE4#41]
Hello,
I'm having an issue building our UE4 (4.11.2) in Win32 Development. The linker is complaining with this error:

2>EXEC : fatal error C1905: Front end and back end not compatible (must target same processor).
2>LINK : fatal error LNK1257: code generation failed

I have verified that FaceFX is what is causing the error and I've verified that the issue happens in a stock version of UE4 4.11.2. It appears that Win64 configs are not affected by this error.

Any advice?
Thanks!
Erik

**Comment by dpakatheman** [comment]
Thanks for pointing this issue out.  For some reason, the /GL flag (Whole Program Optimization) that the release Win32 FaceFX Runtime library is compiled with is causing this error.  We will be releasing new libraries soon.  Until then, the only workaround we are aware of to get a Win32 build working is to build the Debug version after setting bDebugBuildsActuallyUseDebugCRT to true in BuildConfiguration.cs

**Comment by jcredmond** [comment]
Grab the latest version 1.1.1 FaceFX Runtime files from facefx.com and update your plugin source to point to that version and this issue should go away.
