### ISSUE TITLE
MAX_PATH issue on windows

### ISSUE THREAD

**Issue by eirland** [FaceFX/FaceFX-UE4#64]
I'm hitting the 260 character path length maximum due to some of the files in the faceFX runtime folder. While I don't think its the only offender, the files in this path are nested particularly deep:

\facefx-runtime-1.2.0\facefx\tools\compiler\src\extern\yaml-cpp\build\osx\CMakeFiles\3.7.1\CompilerIdC\CompilerIdC.build\Debug\CompilerIdC.build

once the facefx-runtime-1.2.0 is copied into my UE4 workspace (the plugin folder is already nested fairly deeply) I'm violating the limit by ~20 characters. For reference my workspace root for the UE4 engine is ~30 characters.

I don't think any of the missing offending files are causing issues for us at the moment, but it would be nice if this folder would copy cleanly. Is there any way you guys could reorganize the folder structure a bit to alleviate this issue?

Thanks!
Erik

**Comment by jcredmond** [comment]
Can you send us a support email to support@oc3ent.com about this so we can pick up the discussion there? The runtime source is confidential and separate from the UE4 plugin.
