### ISSUE TITLE
FaceFX fails to compile with Visual Studio 2017

### ISSUE THREAD

**Issue by SeanBoocock** [FaceFX/FaceFX-UE4#73]
Unreal 4.14 added provisional support for Visual Studio 2017 and 4.15 has full support for it.  When generating projects and compiling I encountered issues resolving the path to and linking against the runtime libraries.  The root cause for this is in FaceFXLib.Build.cs (ln86):

`string CompilerFolder = WindowsPlatform.Compiler == WindowsCompiler.VisualStudio2015 ? "vs14" : "vs12";`

I modified our version to be:

`string CompilerFolder = (WindowsPlatform.Compiler == WindowsCompiler.VisualStudio2015 || WindowsPlatform.Compiler == WindowsCompiler.VisualStudio2017) ? "vs14" : "vs12";`

Apologies for the lack of a pull request.

**Comment by jcredmond** [comment]
Thanks! We'll make sure this is in the next release.
